### ISSUE TITLE
Improve Azure Services experience based on user research feedback

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#1111]
![newAzureServicesFlow](https://user-images.githubusercontent.com/24245311/63288996-e70d9c80-c272-11e9-999a-56330676601b.png)
![azureServicesFlow-master](https://user-images.githubusercontent.com/24245311/63288560-df012d00-c271-11e9-9fc3-1d49082d5b37.png)
After conducting user testing with intermediate web app developers, the current existing design still doesn't fulfill the knowledge needed to feel confident in adding Azure services to our product. 

Our team has determined that the best way to handle this is through text and visual feedback via a video embedded into the wizard. We also believe a seamless wizard experience is necessary to reduce the friction from adding a service and to create a clear picture of the relationship between the Azure log in to add the Azure services by setting expectations (as shown in the log in/sign up modal) for the user.

### **Task List**

**Azure Sign In Page**
- [x] Create log in/create account modal - @Tanya0609 (#1121)
- [x] Re-route "Add Resource" button to payment modal - @Tanya0609 (#1137)

**Azure Signed In Page**
- [x] Make more apparent you are signed in (#1121)

**Azure Sign In/Signed In Page**
- [x] Add payment & time expectation - @jasmingoh (#1113)
- [x] ~Investigate how to add videos to the wizard~ - @jasmingoh
- [x] ~Create App Service video~
- [x] ~Create Cosmos DB video~
- [ ] Ensure responsiveness of page (reference: https://cloud.google.com/)
- [x] Add section where user is logged in (#1121)
- [x] Remove Azure Functions from preview mode - @jasmingoh (#1122)

**Log In/Create Account Modal**
- [x] Remove Azure Sign In Section - @Tanya0609  (#1137)
- [x] Create copy for log in/create account modal
- [x] Create dropdown behaviour for FAQ to set expectations for user (#1121)

**Azure Forms**
- [ ] If user selects, "Create New" for the subscription part, the entire wizard should be disabled apart from a single refresh function (with option to cancel) so that the user doesn't have to exit out of the form then add it back in
- [x] default "create a new resource group" option and hide resource group section in both forms, since the regular user flow is to put all services related to one project into the same resource group. Here we are creating a new project for them, and create a new resource group too, thus no need to provide "choose existing" option - @jasmingoh (#1117)
- [x] for Cosmos DB, we should remove location selection. Since resource group is created under Central US, then it would make sense to make deployment location into Central US too -@jasmingoh (#1117)

**Comment by Tanya0609** [comment]
Answers to questions in the sign in modal: 
https://azure.microsoft.com/en-us/free/

**Comment by SahilTara** [comment]
>  for Cosmos DB, we should remove location selection. Since resource group is created under Central US, then it would make sense to make deployment location into Central US too.

I think this should only be done when you click create resource group. Otherwise it should still allow you to (I think this is what you meant as well just wanted to be sure)

**Comment by jasmingoh** [comment]
> > US, then it would make sense to make deployment location into Central US too.
> 
> I think this should only be done when you click create resource group. Otherwise it should still allow you to (I think this is what you meant as well just wanted to be sure)

We'll just default everything to Central US

**Comment by xtinah-w** [comment]
@jasmingoh 
![newAzurePageforStudents](https://user-images.githubusercontent.com/24245311/63395336-3ab5de00-c378-11e9-9828-d634409384b2.png)

**Comment by sibille** [comment]
Closing as this seems all to be done + there is a separate issue for improving the "Create New" Subscription experience (https://github.com/microsoft/WebTemplateStudio/issues/996)
