### ISSUE TITLE
Review and update Docs

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WebTemplateStudio#1193]
We should use docs for our documentation and wiki for additional contents and notes

### Docs structure:

:file_folder: Contributing
       :page_facing_up: Accessibility.md
       :page_facing_up: Architecture.md
       :page_facing_up: Getting-started-developers.md
       :page_facing_up: Templates.md

:file_folder: Generated Apps
       :file_folder: Backend-frameworks
              :page_facing_up: Node-js.md
              :page_facing_up: Flask.md
              :page_facing_up: Moleculer.md
       :file_folder: Frontend-frameworks
              :page_facing_up: React.md
              :page_facing_up: Angular.md
              :page_facing_up: Vue-js.md
       :file_folder: Pages
              :page_facing_up: Blank.md
              :page_facing_up: Grid.md
              :page_facing_up: List.md
              :page_facing_up: Master-detail.md
       :file_folder: Services
              :page_facing_up: Azure-cosmosDB.md
              :page_facing_up: Azure-app-service.md
       :page_facing_up: Deployment.md
:file_folder: Resources
       :page_facing_up: Arch-diagram.png
       :page_facing_up: More images

:page_facing_up: acknowledgments.md
:page_facing_up: Concepts.md
:page_facing_up: Faqs.md
:page_facing_up: Install.md
:page_facing_up: Readme.md
:page_facing_up: Telemetry.md
:page_facing_up: TelemetryData.md

### Wiki structure:

:page_facing_up: Home
:page_facing_up: Color themes
:page_facing_up: Internationalization
:page_facing_up: Create Vsix Package 

----------------------------------

### Action Plan:

- [x] Update services docs
- [x] Update contributing documentation
- [x] Update concepts + faq docs
- [x] Add framework docs
- [x] Add pages docs
- [x] Update readme's with links to other pages
- [x] Update wiki

**Comment by dgomezc** [comment]
Review of docs and wiki is finished, updated the first comment of this issue with  proposal for docs and wiki structure and action plan.

Also opened issues #1285 and #1286 for topics that need further work/investigation.

**Comment by sibille** [comment]
Verified in dev
