### ISSUE TITLE
Add App Services

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#888]
Add App Services as an Azure service to deploy the generated web app for our users

Part 1 - Creation of App Service instance
- [x] Add App Service Card (#905)
- [x] Add App Service Form (#914)
- [x] Extension validates name and subscription data (#915)
- [x] Send App Service payload from 'Create Project' button to the extension (#959)
- [x] Add App Service to Right Side Nav if created (#968)
- [x] Allow users to only choose one hosting service (Functions or App Service) (#975)
- [x] Tell users they can only choose one hosting service (new string) (#985)
- [x] Warn users about 30 day free trial for Basic Tier ASP in App Service Form (#995)
- [x] Extension creates resource group (#979)
- [x] Extension creates an ASP (#970)
- [x] Extension creates a web app (#1014)
- [x] Make App Service extension a dependency on our extension (#1007)
- [x] Update post gen modal with App Service (#1026)
- [x] Update the Angular package.json to include all required dependencies (#1059)

Part 2 - Deployment of Generated App
- [x] If App Service is selected, generate `settings.json` in the generated project (#1045)
- [x] Update App Service application settings (#1068)
- [x] Update the generated config files to deploy the server folder (#1072)
- [x] Single command for deploying web app (#1077)

Part 3
- [x] Move App Service card out of preview mode (#1078)

**Comment by xtinah-w** [comment]
App Service Form revisions (some changes apply to all Azure forms)
![appServiceForm](https://user-images.githubusercontent.com/24245311/62240599-2dff2500-b38c-11e9-97f4-bc0a5dbe6c70.png)

**Comment by streetcoder123** [comment]
App service is out of preview :)
